### ISSUE TITLE
ウイルスバスターにランサムウェア扱いされる

### ISSUE THREAD

**Issue by Alice8Flandre** [sk-0520/Pe#844]
データをやり取りをしていると突然終了し、何事かと思うとウイルスバスターから「ランサムウェアのブロック」の通知が表示されることがあります。
![ランサムウェアのブロック 2023_01_06 20_54_30](https://user-images.githubusercontent.com/122095971/211009133-269f6af6-61dc-475a-95d3-1d4a35410a9f.png)

**Comment by sk-0520** [comment]
誤検出ではありますが、もしかしたら何か対応できるかもしれないので `詳細の表示` で表示される情報もいただけないでしょうか。

使用者の数に依存する部分もあり、解決できない確率の方が高いです。

**Comment by Alice8Flandre** [comment]
主に画像を生成したり、移動したりしている際に発生します。
1度目はandroidエミュレータ「BlueStacks」でアプリ「アズールレーン」をプレイ中にBlueStacksのスクリーンショット機能を使った時に、2度目は1度目のエミュレータを起動せず、ただエクスプローラ上でニンテンドー3DSで撮影した画像をHDDに移動している最中にやられました。1度目なんてレア艦船「シェフィールド」を入手したスクショを撮影した瞬間にクラッシュされ、スクショの保存すらさせてもらえませんでした。
![ログ (詳細) 2023_01_11 15_51_22](https://user-images.githubusercontent.com/122095971/211738860-6aec418d-9b7d-4c3f-a9e6-1612fb0892d6.png)
![ウイルスバスターにランサムウェア扱いされる · Issue #844 · sk-0520_Pe — Mozilla Firefox 2023_01_11 15_58_38](https://user-images.githubusercontent.com/122095971/211738892-fb2e3547-7877-4e88-8ba3-1d4457828f6b.png)

**Comment by sk-0520** [comment]
# むずかしい

* `A`
  1. **BlueStacks** を Pe から起動している
  2. **BlueStacks** のスクリーンショット実施
* `B`
  1. なんもしてないけどエクスプローラから何かしらの挙動を行うと Pe が起因で死ぬ
* `C` 
  1. `A`, `B` これら挙動はウィルスバスターのホワイトリストに追加していても発生する

この認識でいいですか？

> 1度目なんてレア艦船「シェフィールド」を入手したスクショを撮影した瞬間にクラッシュされ、スクショの保存すらさせてもらえませんでした。

なんか分かんないですがすいません。

---------

## `C` 次第にはなりますが今のところこうする案

* `A` に関しては Pe が謎アプリ判定されたうえで子プロセスとなる **BlueStacks** が何かしらの問題判定で親プロセスを殺される判定となった
  * WindowsAPI の仕組みでできるか不明ですが Pe を親プロセスとしない回避を行う
* `B` はわかんない……Pe が謎アプリ判定されたうえでキー操作がキーフック処理で死んだ
  * キー操作処理が行われていない場合は注入しない

※ `A` はまだわからなくもないですが、 `B` が分からない。。。

---

* チート対策処理がウィルスバスターに組み込まれてて Pe 側のフック処理が誤認された、ならばわかりやすいんですがいまいち分からない
* あと個人的には Windows のセキュリティ対策で満足してるので再現がつらいです（ついでにスマホゲームしない・・・

**Comment by sk-0520** [comment]
**B**でしたか。 とりあえず例外リストへの設定が一番問題なさそうですかね。

> さっきまた B のパターンをやられた

ソースを眺めてきたのですがキー設定の有無でキーボードフックの適用という実装なので実装回避は難しいかもしれません。  
※再現環境がないので何ともですが

例外リスト追加で稼働しているようなので本件は一旦閉じます。
